service: weather-check-lambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  deploymentBucket:
    name: ${aws:accountId}-bucket
  environment:
    API_URL: https://api.openweathermap.org/data/2.5/weather?q=%CITY%&appid=%APIKEY%&units=metric
    API_KEY: 749561a315b14523a8f5f1ef95e45864

package:
  artifact: target/weather-check-lambda.jar

functions:
  hello:
    handler: com.mateuszjanczak.weatherchecklambda.Handler
    events:
      - httpApi:
          path: /weather
          method: post